### ISSUE TITLE
Possible licence issue with `Xceed.Wpf.Toolkit`

### ISSUE THREAD

**Issue by FroggieFrog** [ChrisPulman/VS.Squirrel#133]
Because you are using a version > `3.8` of the `Xceed.Wpf.Toolkit` there could be an issue with the licence.
See this issue where the maintainer **does not** deny the issue: [xceedsoftware/wpftoolkit#1598](https://github.com/xceedsoftware/wpftoolkit/issues/1598)

Do you have other/additional information on this topic?

**Comment by ChrisPulman** [comment]
This package has now been removed, thanks
